import './styles/style.scss';
import './js/prices.js';
import './js/main-menu.js';
import './js/main-content.js';
import './js/brends.js';
import './js/technics.js';
import './js/prices.js'
import './js/mobil-menu.js';
import './js/mobil-popap.js';
import './js/feedback-popap.js';
import './js/request-popap.js';
